module.exports = {
    ERRORS: {
        // 初始化错误
        ERR_WHEN_INIT_SDK: 'ERR_WHEN_INIT_SDK',
        ERR_INIT_SDK_LOST_CONFIG: 'ERR_INIT_SDK_LOST_CONFIG',
        ERR_INIT_SDK_LOST_MYSQL_CONFIG:'ERR_INIT_SDK_LOST_MYSQL_CONFIG',
        ERR_WHEN_INIT_MYSQL: 'ERR_WHEN_INIT_MYSQL',

        // 统一下单模块
        ERR_UNIFIEDORDER: 'ERR_UNIFIEDORDER',
        ERR_REQ_PARAM_MISSED: 'ERR_REQ_PARAM_MISSED',
        ERR_GET_UNIFIEDOREDER:'ERR_GET_UNIFIEDOREDER',

        // 数据库错误
        DBERR: {
            ERR_WHEN_INSERT_TO_DB: 'ERR_WHEN_INSERT_TO_DB',
            ERR_WHEN_UPDATE_TO_DB: 'ERR_WHEN_UPDATE_TO_DB',
            ERR_NO_ORDER_FOUND:'ERR_NO_ORDER_FOUND'
        }
    },
    ORDER_STATE: {
        INIT: 0,    // 创建订单
        UNIFIED: 1  // 统一下单
    }
}
